# Generated by Django 3.1.1 on 2020-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
