# Generated by Django 3.1.1 on 2020-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200928_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='web_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
